[2025-02-07T06:47:10.289+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T06:47:10.298+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T06:47:08.075920+00:00 [queued]>
[2025-02-07T06:47:10.301+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T06:47:08.075920+00:00 [queued]>
[2025-02-07T06:47:10.302+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T06:47:10.310+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-07 06:47:08.075920+00:00
[2025-02-07T06:47:10.316+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1417) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T06:47:10.317+0000] {standard_task_runner.py:72} INFO - Started process 1418 to run task
[2025-02-07T06:47:10.318+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'manual__2025-02-07T06:47:08.075920+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmp_iagsxvx']
[2025-02-07T06:47:10.319+0000] {standard_task_runner.py:105} INFO - Job 227: Subtask rabbitmq_consumer
[2025-02-07T06:47:10.350+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T06:47:08.075920+00:00 [running]> on host 3aa1f743f988
[2025-02-07T06:47:10.404+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T06:47:08.075920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T06:47:08.075920+00:00'
[2025-02-07T06:47:10.405+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T06:47:10.405+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T06:47:10.405+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-07 06:47:10.298766+00:00
[2025-02-07T06:47:10.405+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-07T06:47:10.405+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T06:47:10.407+0000] {logging_mixin.py:190} INFO - RABBITMQ_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
[2025-02-07T06:47:10.409+0000] {selector_ioloop_adapter.py:569} ERROR - Address resolution failed: gaierror(-2, 'Name or service not known')
[2025-02-07T06:47:10.410+0000] {connection_workflow.py:799} ERROR - getaddrinfo failed: gaierror(-2, 'Name or service not known').
[2025-02-07T06:47:10.411+0000] {connection_workflow.py:746} ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None.
[2025-02-07T06:47:10.411+0000] {connection_workflow.py:723} ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None
[2025-02-07T06:47:10.411+0000] {blocking_connection.py:450} ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None
[2025-02-07T06:47:10.411+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
[2025-02-07T06:47:10.413+0000] {logging_mixin.py:190} INFO - Error in listener: [Errno -2] Name or service not known
[2025-02-07T06:47:10.413+0000] {logging_mixin.py:190} INFO - Listener stopped.
[2025-02-07T06:47:10.413+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-07T06:47:10.419+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T06:47:10.419+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=rabbitmq_consumer, run_id=manual__2025-02-07T06:47:08.075920+00:00, execution_date=20250207T064708, start_date=20250207T064710, end_date=20250207T064710
[2025-02-07T06:47:10.424+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T06:47:10.424+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T06:47:10.424+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-07 06:47:08.084826+00:00
[2025-02-07T06:47:10.424+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-07T06:47:10.463+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T06:47:10.474+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T06:47:10.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
