[2025-02-07T07:07:47.345+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T07:07:47.358+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:07:45.303660+00:00 [queued]>
[2025-02-07T07:07:47.369+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:07:45.303660+00:00 [queued]>
[2025-02-07T07:07:47.370+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T07:07:47.388+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-07 07:07:45.303660+00:00
[2025-02-07T07:07:47.398+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1757) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T07:07:47.405+0000] {standard_task_runner.py:72} INFO - Started process 1758 to run task
[2025-02-07T07:07:47.407+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'manual__2025-02-07T07:07:45.303660+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpd5bwv4f5']
[2025-02-07T07:07:47.408+0000] {standard_task_runner.py:105} INFO - Job 237: Subtask rabbitmq_consumer
[2025-02-07T07:07:47.471+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:07:45.303660+00:00 [running]> on host 3aa1f743f988
[2025-02-07T07:07:47.536+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T07:07:45.303660+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T07:07:45.303660+00:00'
[2025-02-07T07:07:47.537+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T07:07:47.537+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T07:07:47.537+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-07 07:07:47.358873+00:00
[2025-02-07T07:07:47.538+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-07T07:07:47.538+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T07:07:47.539+0000] {logging_mixin.py:190} INFO - RABBITMQ_URL: amqp://rabbitmq:rabbitmq@localhost:5672
[2025-02-07T07:07:47.539+0000] {logging_mixin.py:190} INFO - RabbitMQ Host: localhost
[2025-02-07T07:07:47.540+0000] {logging_mixin.py:190} INFO - RabbitMQ Port: 5672
[2025-02-07T07:07:47.543+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
[2025-02-07T07:07:47.544+0000] {io_services_utils.py:349} ERROR - Socket failed to connect: <socket.socket fd=93, family=10, type=1, proto=6, laddr=('::1', 53926, 0, 0)>; error=111 (Connection refused)
[2025-02-07T07:07:47.544+0000] {connection_workflow.py:375} ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(10, 1, 6, '', ('::1', 5672, 0, 0))
[2025-02-07T07:07:47.545+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-07T07:07:47.547+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
[2025-02-07T07:07:47.548+0000] {io_services_utils.py:349} ERROR - Socket failed to connect: <socket.socket fd=93, family=2, type=1, proto=6, laddr=('127.0.0.1', 52262)>; error=111 (Connection refused)
[2025-02-07T07:07:47.548+0000] {connection_workflow.py:375} ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(2, 1, 6, '', ('127.0.0.1', 5672))
[2025-02-07T07:07:47.548+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-07T07:07:47.549+0000] {connection_workflow.py:746} ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused').
[2025-02-07T07:07:47.549+0000] {connection_workflow.py:723} ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-07T07:07:47.549+0000] {blocking_connection.py:450} ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-02-07T07:07:47.550+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
[2025-02-07T07:07:47.551+0000] {logging_mixin.py:190} INFO - Error in listener: 
[2025-02-07T07:07:47.552+0000] {logging_mixin.py:190} INFO - Listener stopped.
[2025-02-07T07:07:47.552+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-07T07:07:47.558+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T07:07:47.558+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=rabbitmq_consumer, run_id=manual__2025-02-07T07:07:45.303660+00:00, execution_date=20250207T070745, start_date=20250207T070747, end_date=20250207T070747
[2025-02-07T07:07:47.564+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T07:07:47.565+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T07:07:47.565+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-07 07:07:45.310930+00:00
[2025-02-07T07:07:47.565+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-07T07:07:47.594+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T07:07:47.613+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T07:07:47.614+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
