[2025-02-23T13:24:34.724+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T13:24:34.752+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T13:23:54.653402+00:00 [queued]>
[2025-02-23T13:24:34.776+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T13:23:54.653402+00:00 [queued]>
[2025-02-23T13:24:34.776+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-23T13:24:34.813+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_notification> on 2025-02-23 13:23:54.653402+00:00
[2025-02-23T13:24:34.841+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=473) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T13:24:34.843+0000] {standard_task_runner.py:72} INFO - Started process 474 to run task
[2025-02-23T13:24:34.845+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'send_notification', 'manual__2025-02-23T13:23:54.653402+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpev_8croc']
[2025-02-23T13:24:34.847+0000] {standard_task_runner.py:105} INFO - Job 412: Subtask send_notification
[2025-02-23T13:24:34.952+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.send_notification manual__2025-02-23T13:23:54.653402+00:00 [running]> on host 9d363d0f65d2
[2025-02-23T13:24:35.147+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='send_notification' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T13:23:54.653402+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T13:23:54.653402+00:00'
[2025-02-23T13:24:35.151+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-23T13:24:35.151+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-23T13:24:35.152+0000] {logging_mixin.py:190} INFO - Current task name:send_notification state:running start_date:2025-02-23 13:24:34.753135+00:00
[2025-02-23T13:24:35.153+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-23T13:24:35.154+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-23T13:24:35.182+0000] {python.py:240} INFO - Done. Returned value was: Failed to send notification: HTTPConnectionPool(host='localhost', port=4000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1740317075.1624205 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff779cbef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-02-23T13:24:35.220+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-23T13:24:35.221+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=send_notification, run_id=manual__2025-02-23T13:23:54.653402+00:00, execution_date=20250223T132354, start_date=20250223T132434, end_date=20250223T132435
[2025-02-23T13:24:35.239+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-23T13:24:35.240+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-23T13:24:35.242+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-23 13:23:55.272314+00:00
[2025-02-23T13:24:35.242+0000] {logging_mixin.py:190} INFO - Task hostname:9d363d0f65d2 operator:PythonOperator
[2025-02-23T13:24:35.279+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T13:24:35.346+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T13:24:35.354+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
