[2025-02-07T07:53:18.836+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T07:53:18.846+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:53:16.039990+00:00 [queued]>
[2025-02-07T07:53:18.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:53:16.039990+00:00 [queued]>
[2025-02-07T07:53:18.850+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T07:53:18.857+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-07 07:53:16.039990+00:00
[2025-02-07T07:53:18.864+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=485) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T07:53:18.866+0000] {standard_task_runner.py:72} INFO - Started process 486 to run task
[2025-02-07T07:53:18.866+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'manual__2025-02-07T07:53:16.039990+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpd_js035f']
[2025-02-07T07:53:18.867+0000] {standard_task_runner.py:105} INFO - Job 254: Subtask rabbitmq_consumer
[2025-02-07T07:53:18.902+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:53:16.039990+00:00 [running]> on host 3aa1f743f988
[2025-02-07T07:53:18.967+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T07:53:16.039990+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T07:53:16.039990+00:00'
[2025-02-07T07:53:18.969+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T07:53:18.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T07:53:18.969+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-07 07:53:18.846371+00:00
[2025-02-07T07:53:18.969+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-07T07:53:18.970+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T07:53:18.974+0000] {logging_mixin.py:190} INFO - RABBITMQ_URL: amqp://rabbitmq:rabbitmq@localhost:5672
[2025-02-07T07:53:18.974+0000] {logging_mixin.py:190} INFO - RabbitMQ Host: localhost
[2025-02-07T07:53:18.974+0000] {logging_mixin.py:190} INFO - RabbitMQ Port: 5672
[2025-02-07T07:53:18.976+0000] {logging_mixin.py:190} INFO - Error in listener: 'AMQPConnectionWorkflow' object has no attribute 'channel'
[2025-02-07T07:53:18.976+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 67, in rabbitmq_consumer
    connection.close()
    ^^^^^^^^^^^^^^^^
AttributeError: 'AMQPConnectionWorkflow' object has no attribute 'close'. Did you mean: '_close'?
[2025-02-07T07:53:18.991+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-07T07:53:18.991+0000] {logging_mixin.py:190} INFO - Task start:2025-02-07 07:53:18.846371+00:00 end:2025-02-07 07:53:18.990880+00:00 duration:0.144509
[2025-02-07T07:53:18.992+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): rabbitmq_consumer> dag:<DAG: idp> dagrun:<DagRun idp @ 2025-02-07 07:53:16.039990+00:00: manual__2025-02-07T07:53:16.039990+00:00, state:running, queued_at: 2025-02-07 07:53:16.049280+00:00. externally triggered: True>
[2025-02-07T07:53:18.992+0000] {logging_mixin.py:190} INFO - Failure caused by 'AMQPConnectionWorkflow' object has no attribute 'close'
[2025-02-07T07:53:18.992+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=idp, task_id=rabbitmq_consumer, run_id=manual__2025-02-07T07:53:16.039990+00:00, execution_date=20250207T075316, start_date=20250207T075318, end_date=20250207T075318
[2025-02-07T07:53:19.009+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T07:53:19.009+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 254 for task rabbitmq_consumer ('AMQPConnectionWorkflow' object has no attribute 'close'; 486)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 67, in rabbitmq_consumer
    connection.close()
    ^^^^^^^^^^^^^^^^
AttributeError: 'AMQPConnectionWorkflow' object has no attribute 'close'. Did you mean: '_close'?
[2025-02-07T07:53:19.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T07:53:19.083+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T07:53:19.084+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
