[2025-02-07T07:11:25.720+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T07:11:25.731+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:11:24.274676+00:00 [queued]>
[2025-02-07T07:11:25.736+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:11:24.274676+00:00 [queued]>
[2025-02-07T07:11:25.737+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T07:11:25.745+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-07 07:11:24.274676+00:00
[2025-02-07T07:11:25.754+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1820) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T07:11:25.758+0000] {standard_task_runner.py:72} INFO - Started process 1821 to run task
[2025-02-07T07:11:25.758+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'manual__2025-02-07T07:11:24.274676+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpxdrz25__']
[2025-02-07T07:11:25.761+0000] {standard_task_runner.py:105} INFO - Job 239: Subtask rabbitmq_consumer
[2025-02-07T07:11:25.866+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T07:11:24.274676+00:00 [running]> on host 3aa1f743f988
[2025-02-07T07:11:26.012+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T07:11:24.274676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T07:11:24.274676+00:00'
[2025-02-07T07:11:26.015+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T07:11:26.015+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T07:11:26.015+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-07 07:11:25.732012+00:00
[2025-02-07T07:11:26.016+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-07T07:11:26.016+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T07:11:26.018+0000] {logging_mixin.py:190} INFO - RABBITMQ_URL: amqp://rabbitmq:rabbitmq@localhost:5672
[2025-02-07T07:11:26.019+0000] {logging_mixin.py:190} INFO - RabbitMQ Host: orchestronic-rabbitmq-1
[2025-02-07T07:11:26.019+0000] {logging_mixin.py:190} INFO - RabbitMQ Port: 5672
[2025-02-07T07:11:26.022+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.19.0.8', 5672)
[2025-02-07T07:11:26.024+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.4', 34128), raddr=('172.19.0.8', 5672)>
[2025-02-07T07:11:26.028+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffffa5abcec0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0xffffa5abcec0> params=<ConnectionParameters host=orchestronic-rabbitmq-1 port=5672 virtual_host=/ ssl=False>>).
[2025-02-07T07:11:26.033+0000] {io_services_utils.py:731} INFO - Aborting transport connection: state=1; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.4', 34128), raddr=('172.19.0.8', 5672)>
[2025-02-07T07:11:26.033+0000] {io_services_utils.py:904} INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.4', 34128), raddr=('172.19.0.8', 5672)>
[2025-02-07T07:11:26.033+0000] {io_services_utils.py:869} INFO - Deactivating transport: state=1; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.4', 34128), raddr=('172.19.0.8', 5672)>
[2025-02-07T07:11:26.034+0000] {connection.py:2017} INFO - AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
[2025-02-07T07:11:26.034+0000] {connection.py:2052} ERROR - Connection closed while authenticating indicating a probable authentication error
[2025-02-07T07:11:26.034+0000] {connection.py:2082} INFO - Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
[2025-02-07T07:11:26.035+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
[2025-02-07T07:11:26.036+0000] {connection_workflow.py:746} ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None.
[2025-02-07T07:11:26.036+0000] {connection_workflow.py:723} ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None
[2025-02-07T07:11:26.036+0000] {io_services_utils.py:882} INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=93, family=2, type=1, proto=6, laddr=('172.19.0.4', 34128), raddr=('172.19.0.8', 5672)>
[2025-02-07T07:11:26.037+0000] {blocking_connection.py:450} ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - None
[2025-02-07T07:11:26.038+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
[2025-02-07T07:11:26.041+0000] {logging_mixin.py:190} INFO - Error in listener: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
[2025-02-07T07:11:26.041+0000] {logging_mixin.py:190} INFO - Listener stopped.
[2025-02-07T07:11:26.042+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-07T07:11:26.049+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T07:11:26.049+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=rabbitmq_consumer, run_id=manual__2025-02-07T07:11:24.274676+00:00, execution_date=20250207T071124, start_date=20250207T071125, end_date=20250207T071126
[2025-02-07T07:11:26.062+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T07:11:26.063+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T07:11:26.063+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-07 07:11:24.286162+00:00
[2025-02-07T07:11:26.064+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-07T07:11:26.113+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T07:11:26.136+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T07:11:26.137+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
