[2025-02-09T13:56:16.391+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T13:56:16.409+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-09T13:56:16.430+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-09T13:56:16.431+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-09T13:56:16.443+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-08 00:00:00+00:00
[2025-02-09T13:56:16.465+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T13:56:16.466+0000] {standard_task_runner.py:72} INFO - Started process 72 to run task
[2025-02-09T13:56:16.466+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpz9_io9hf']
[2025-02-09T13:56:16.467+0000] {standard_task_runner.py:105} INFO - Job 303: Subtask rabbitmq_consumer
[2025-02-09T13:56:16.511+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer scheduled__2025-02-08T00:00:00+00:00 [running]> on host 3aa1f743f988
[2025-02-09T13:56:16.567+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-09T13:56:16.568+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T13:56:16.568+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T13:56:16.570+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-09 13:56:16.413486+00:00
[2025-02-09T13:56:16.571+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-09T13:56:16.572+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T13:56:17.036+0000] {selector_ioloop_adapter.py:569} ERROR - Address resolution failed: gaierror(-2, 'Name or service not known')
[2025-02-09T13:56:17.041+0000] {connection_workflow.py:799} ERROR - getaddrinfo failed: gaierror(-2, 'Name or service not known').
[2025-02-09T13:56:17.045+0000] {connection_workflow.py:746} ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None.
[2025-02-09T13:56:17.046+0000] {connection_workflow.py:723} ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None
[2025-02-09T13:56:17.046+0000] {blocking_connection.py:450} ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None
[2025-02-09T13:56:17.046+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
[2025-02-09T13:56:17.050+0000] {logging_mixin.py:190} INFO - Error in listener: [Errno -2] Name or service not known
[2025-02-09T13:56:17.050+0000] {logging_mixin.py:190} INFO - Listener stopped.
[2025-02-09T13:56:17.051+0000] {python.py:240} INFO - Done. Returned value was: 
[2025-02-09T13:56:17.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T13:56:17.073+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=rabbitmq_consumer, run_id=scheduled__2025-02-08T00:00:00+00:00, execution_date=20250208T000000, start_date=20250209T135616, end_date=20250209T135617
[2025-02-09T13:56:17.081+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-09T13:56:17.082+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-09T13:56:17.082+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-09 13:56:09.256277+00:00
[2025-02-09T13:56:17.083+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-09T13:56:17.116+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T13:56:17.151+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-09T13:56:17.152+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
