[2025-02-23T11:48:11.564+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T11:48:11.604+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T10:58:33.806381+00:00 [queued]>
[2025-02-23T11:48:11.646+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T10:58:33.806381+00:00 [queued]>
[2025-02-23T11:48:11.648+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-23T11:48:11.687+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_notification> on 2025-02-23 10:58:33.806381+00:00
[2025-02-23T11:48:11.721+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2678) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T11:48:11.728+0000] {standard_task_runner.py:72} INFO - Started process 2679 to run task
[2025-02-23T11:48:11.730+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'send_notification', 'manual__2025-02-23T10:58:33.806381+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpbtf65ki8']
[2025-02-23T11:48:11.732+0000] {standard_task_runner.py:105} INFO - Job 398: Subtask send_notification
[2025-02-23T11:48:11.873+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.send_notification manual__2025-02-23T10:58:33.806381+00:00 [running]> on host 9d363d0f65d2
[2025-02-23T11:48:12.182+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='send_notification' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T10:58:33.806381+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T10:58:33.806381+00:00'
[2025-02-23T11:48:12.193+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-23T11:48:12.194+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-23T11:48:12.198+0000] {logging_mixin.py:190} INFO - Current task name:send_notification state:running start_date:2025-02-23 11:48:11.606094+00:00
[2025-02-23T11:48:12.201+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-23T11:48:12.201+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-23T11:48:12.931+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 135, in send_notification
    sio.connect('http://localhost:4000')
    ^^^^^^^^^^^
AttributeError: 'Server' object has no attribute 'connect'. Did you mean: 'disconnect'?
[2025-02-23T11:48:12.983+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-23T11:48:12.984+0000] {logging_mixin.py:190} INFO - Task start:2025-02-23 11:48:11.606094+00:00 end:2025-02-23 11:48:12.980985+00:00 duration:1.374891
[2025-02-23T11:48:12.987+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): send_notification> dag:<DAG: idp> dagrun:<DagRun idp @ 2025-02-23 10:58:33.806381+00:00: manual__2025-02-23T10:58:33.806381+00:00, state:running, queued_at: 2025-02-23 10:58:34.071506+00:00. externally triggered: True>
[2025-02-23T11:48:12.991+0000] {logging_mixin.py:190} INFO - Failure caused by 'Server' object has no attribute 'connect'
[2025-02-23T11:48:12.993+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=idp, task_id=send_notification, run_id=manual__2025-02-23T10:58:33.806381+00:00, execution_date=20250223T105833, start_date=20250223T114811, end_date=20250223T114812
[2025-02-23T11:48:13.057+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-23T11:48:13.061+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 398 for task send_notification ('Server' object has no attribute 'connect'; 2679)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 135, in send_notification
    sio.connect('http://localhost:4000')
    ^^^^^^^^^^^
AttributeError: 'Server' object has no attribute 'connect'. Did you mean: 'disconnect'?
[2025-02-23T11:48:13.152+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-23T11:48:13.199+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
