[2025-02-23T13:05:17.636+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T13:05:17.680+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T13:02:58.235178+00:00 [queued]>
[2025-02-23T13:05:17.710+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T13:02:58.235178+00:00 [queued]>
[2025-02-23T13:05:17.711+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-23T13:05:17.802+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_notification> on 2025-02-23 13:02:58.235178+00:00
[2025-02-23T13:05:17.845+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T13:05:17.857+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'send_notification', 'manual__2025-02-23T13:02:58.235178+00:00', '--job-id', '406', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpgzed81a1']
[2025-02-23T13:05:17.864+0000] {standard_task_runner.py:72} INFO - Started process 246 to run task
[2025-02-23T13:05:17.864+0000] {standard_task_runner.py:105} INFO - Job 406: Subtask send_notification
[2025-02-23T13:05:18.167+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.send_notification manual__2025-02-23T13:02:58.235178+00:00 [running]> on host 9d363d0f65d2
[2025-02-23T13:05:18.561+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='send_notification' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T13:02:58.235178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T13:02:58.235178+00:00'
[2025-02-23T13:05:18.576+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-23T13:05:18.577+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-23T13:05:18.579+0000] {logging_mixin.py:190} INFO - Current task name:send_notification state:running start_date:2025-02-23 13:05:17.680998+00:00
[2025-02-23T13:05:18.582+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-23T13:05:18.582+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-23T13:05:18.636+0000] {python.py:240} INFO - Done. Returned value was: Failed to send notification: HTTPConnectionPool(host='localhost', port=4000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1740315918.6029356 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7790bfe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-02-23T13:05:18.703+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-23T13:05:18.711+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=send_notification, run_id=manual__2025-02-23T13:02:58.235178+00:00, execution_date=20250223T130258, start_date=20250223T130517, end_date=20250223T130518
[2025-02-23T13:05:18.764+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-23T13:05:18.765+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-23T13:05:18.765+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-23 13:02:58.274410+00:00
[2025-02-23T13:05:18.766+0000] {logging_mixin.py:190} INFO - Task hostname:9d363d0f65d2 operator:PythonOperator
[2025-02-23T13:05:18.815+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T13:05:18.886+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T13:05:18.935+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
