[2025-02-07T06:19:26.207+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T06:19:26.221+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T06:19:24.120632+00:00 [queued]>
[2025-02-07T06:19:26.230+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T06:19:24.120632+00:00 [queued]>
[2025-02-07T06:19:26.231+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T06:19:26.240+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): rabbitmq_consumer> on 2025-02-07 06:19:24.120632+00:00
[2025-02-07T06:19:26.258+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=951) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T06:19:26.260+0000] {standard_task_runner.py:72} INFO - Started process 952 to run task
[2025-02-07T06:19:26.260+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'rabbitmq_consumer', 'manual__2025-02-07T06:19:24.120632+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmp1h9cbyiw']
[2025-02-07T06:19:26.263+0000] {standard_task_runner.py:105} INFO - Job 210: Subtask rabbitmq_consumer
[2025-02-07T06:19:26.327+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.rabbitmq_consumer manual__2025-02-07T06:19:24.120632+00:00 [running]> on host 3aa1f743f988
[2025-02-07T06:19:26.409+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='rabbitmq_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T06:19:24.120632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T06:19:24.120632+00:00'
[2025-02-07T06:19:26.410+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T06:19:26.410+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T06:19:26.411+0000] {logging_mixin.py:190} INFO - Current task name:rabbitmq_consumer state:running start_date:2025-02-07 06:19:26.222333+00:00
[2025-02-07T06:19:26.411+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-07T06:19:26.411+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T06:19:26.412+0000] {logging_mixin.py:190} INFO - Error in listener: RABBITMQ_URL is not set
[2025-02-07T06:19:26.412+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 45, in rabbitmq_consumer
    connection.close()
    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connection' where it is not associated with a value
[2025-02-07T06:19:26.424+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-07T06:19:26.424+0000] {logging_mixin.py:190} INFO - Task start:2025-02-07 06:19:26.222333+00:00 end:2025-02-07 06:19:26.424109+00:00 duration:0.201776
[2025-02-07T06:19:26.425+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): rabbitmq_consumer> dag:<DAG: idp> dagrun:<DagRun idp @ 2025-02-07 06:19:24.120632+00:00: manual__2025-02-07T06:19:24.120632+00:00, state:running, queued_at: 2025-02-07 06:19:24.139298+00:00. externally triggered: True>
[2025-02-07T06:19:26.425+0000] {logging_mixin.py:190} INFO - Failure caused by cannot access local variable 'connection' where it is not associated with a value
[2025-02-07T06:19:26.425+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=idp, task_id=rabbitmq_consumer, run_id=manual__2025-02-07T06:19:24.120632+00:00, execution_date=20250207T061924, start_date=20250207T061926, end_date=20250207T061926
[2025-02-07T06:19:26.438+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T06:19:26.438+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 210 for task rabbitmq_consumer (cannot access local variable 'connection' where it is not associated with a value; 952)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 45, in rabbitmq_consumer
    connection.close()
    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'connection' where it is not associated with a value
[2025-02-07T06:19:26.446+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T06:19:26.464+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T06:19:26.465+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
