[2025-02-23T13:20:33.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T13:20:33.843+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T13:20:06.520860+00:00 [queued]>
[2025-02-23T13:20:33.852+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.send_notification manual__2025-02-23T13:20:06.520860+00:00 [queued]>
[2025-02-23T13:20:33.852+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-23T13:20:33.872+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): send_notification> on 2025-02-23 13:20:06.520860+00:00
[2025-02-23T13:20:33.885+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=415) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T13:20:33.887+0000] {standard_task_runner.py:72} INFO - Started process 416 to run task
[2025-02-23T13:20:33.889+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'send_notification', 'manual__2025-02-23T13:20:06.520860+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpl_cgdt1w']
[2025-02-23T13:20:33.899+0000] {standard_task_runner.py:105} INFO - Job 409: Subtask send_notification
[2025-02-23T13:20:34.009+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.send_notification manual__2025-02-23T13:20:06.520860+00:00 [running]> on host 9d363d0f65d2
[2025-02-23T13:20:34.170+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='send_notification' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T13:20:06.520860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-23T13:20:06.520860+00:00'
[2025-02-23T13:20:34.177+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-23T13:20:34.178+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-23T13:20:34.178+0000] {logging_mixin.py:190} INFO - Current task name:send_notification state:running start_date:2025-02-23 13:20:33.845124+00:00
[2025-02-23T13:20:34.179+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-02-23T13:20:34.180+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-23T13:20:34.246+0000] {python.py:240} INFO - Done. Returned value was: Failed to send notification: HTTPConnectionPool(host='localhost', port=4000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1740316834.1962929 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff778bb770>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-02-23T13:20:34.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-23T13:20:34.376+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=send_notification, run_id=manual__2025-02-23T13:20:06.520860+00:00, execution_date=20250223T132006, start_date=20250223T132033, end_date=20250223T132034
[2025-02-23T13:20:34.441+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-23T13:20:34.446+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-23T13:20:34.446+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-02-23 13:20:06.665073+00:00
[2025-02-23T13:20:34.447+0000] {logging_mixin.py:190} INFO - Task hostname:9d363d0f65d2 operator:PythonOperator
[2025-02-23T13:20:34.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T13:20:34.552+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T13:20:34.564+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
