[2025-02-04T13:46:34.979+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T13:46:34.995+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp_fetch_mongo.fetch_from_mongo scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-04T13:46:35.001+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp_fetch_mongo.fetch_from_mongo scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-04T13:46:35.002+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-04T13:46:35.020+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_from_mongo> on 2025-02-03 00:00:00+00:00
[2025-02-04T13:46:35.040+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4807) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T13:46:35.047+0000] {standard_task_runner.py:72} INFO - Started process 4809 to run task
[2025-02-04T13:46:35.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp_fetch_mongo', 'fetch_from_mongo', 'scheduled__2025-02-03T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmp5kh09710']
[2025-02-04T13:46:35.049+0000] {standard_task_runner.py:105} INFO - Job 183: Subtask fetch_from_mongo
[2025-02-04T13:46:35.150+0000] {task_command.py:467} INFO - Running <TaskInstance: idp_fetch_mongo.fetch_from_mongo scheduled__2025-02-03T00:00:00+00:00 [running]> on host 3aa1f743f988
[2025-02-04T13:46:35.243+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp_fetch_mongo' AIRFLOW_CTX_TASK_ID='fetch_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T00:00:00+00:00'
[2025-02-04T13:46:35.245+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-04T13:46:35.245+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-04T13:46:35.246+0000] {logging_mixin.py:190} INFO - Current task name:fetch_from_mongo state:running start_date:2025-02-04 13:46:34.995631+00:00
[2025-02-04T13:46:35.246+0000] {logging_mixin.py:190} INFO - Dag name:idp_fetch_mongo and current dag run status:running
[2025-02-04T13:46:35.246+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T13:46:35.247+0000] {logging_mixin.py:190} INFO - All environment variables: environ({'AIRFLOW__CELERY__RESULT_BACKEND': 'db+postgresql://***:***@postgres/***', 'PYTHON_SHA256': 'c909157bb25ec114e5869124cc2a9c4a4d4c1e957ca4ff553f1edc692101154e', 'DUMB_INIT_SETSID': '0', 'HOSTNAME': '3aa1f743f988', 'PYTHON_VERSION': '3.12.8', 'LANGUAGE': 'C.UTF-8', 'AIRFLOW_USER_HOME_DIR': '/home/***', 'ADDITIONAL_RUNTIME_APT_DEPS': '', 'PWD': '/opt/***', 'AIRFLOW__CELERY__BROKER_URL': 'redis://:@redis:6379/0', 'AIRFLOW_VERSION': '2.10.4', 'AIRFLOW__CORE__LOAD_EXAMPLES': 'true', 'AIRFLOW__API__AUTH_BACKENDS': '***.api.auth.backend.basic_auth,***.api.auth.backend.session', 'INSTALL_MSSQL_CLIENT': 'true', 'INSTALL_MYSQL_CLIENT_TYPE': 'mariadb', 'GUNICORN_CMD_ARGS': '--worker-tmp-dir /dev/shm', 'LD_PRELOAD': '/usr/lib/aarch64-linux-gnu/libstdc++.so.6', 'HOME': '/home/***', 'LANG': 'C.UTF-8', 'VIRTUAL_ENV': '/home/***/.local', 'AIRFLOW_HOME': '/opt/***', 'GPG_KEY': '7169605F62C751356D054A26A821E680E5FA6305', 'AIRFLOW__DATABASE__SQL_ALCHEMY_CONN': '***', 'AIRFLOW_USE_UV': 'false', 'AIRFLOW__CORE__EXECUTOR': 'CeleryExecutor', 'COMMIT_SHA': 'c083e456fa02c6cb32cdbe0c9ed3c3b2380beccd', 'AIRFLOW_PIP_VERSION': '24.3.1', 'AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION': 'true', 'ADDITIONAL_RUNTIME_APT_COMMAND': '', 'AIRFLOW_UV_VERSION': '0.4.29', '_PIP_ADDITIONAL_REQUIREMENTS': '', 'INSTALL_POSTGRES_CLIENT': 'true', 'SHLVL': '0', 'LC_MESSAGES': 'C.UTF-8', 'RUNTIME_APT_DEPS': '', 'RUNTIME_APT_COMMAND': 'echo', 'LD_LIBRARY_PATH': '/usr/local/lib', 'LC_CTYPE': 'C.UTF-8', 'AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK': 'true', 'AIRFLOW_INSTALLATION_METHOD': '', 'LC_ALL': 'C.UTF-8', 'INSTALL_MYSQL_CLIENT': 'true', 'PATH': '/root/bin:/home/***/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'PYTHON_BASE_IMAGE': 'python:3.12-slim-bookworm', 'AIRFLOW_UID': '50000', 'BUILD_ID': '', 'AIRFLOW__CORE__FERNET_KEY': '', 'DEBIAN_FRONTEND': 'noninteractive', '_MP_FORK_LOGLEVEL_': '20', '_MP_FORK_LOGFILE_': '', '_MP_FORK_LOGFORMAT_': '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s', 'CELERY_LOG_LEVEL': '20', 'CELERY_LOG_FILE': '', 'CELERY_LOG_REDIRECT': '1', 'CELERY_LOG_REDIRECT_LEVEL': 'WARNING', '_AIRFLOW_PARSING_CONTEXT_DAG_ID': 'idp_fetch_mongo', '_AIRFLOW_PARSING_CONTEXT_TASK_ID': 'fetch_from_mongo', 'AIRFLOW_CTX_DAG_OWNER': '***', 'AIRFLOW_CTX_DAG_ID': 'idp_fetch_mongo', 'AIRFLOW_CTX_TASK_ID': 'fetch_from_mongo', 'AIRFLOW_CTX_EXECUTION_DATE': '2025-02-03T00:00:00+00:00', 'AIRFLOW_CTX_TRY_NUMBER': '2', 'AIRFLOW_CTX_DAG_RUN_ID': 'scheduled__2025-02-03T00:00:00+00:00'})
[2025-02-04T13:46:35.248+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/idp.py", line 17, in fetch_from_mongo
    raise Exception("MONGODB_URI is not set")
Exception: MONGODB_URI is not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/idp.py", line 39, in fetch_from_mongo
    raise Exception(f"The following error occurred: {str(e)}")
Exception: The following error occurred: MONGODB_URI is not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 42, in fetch_from_mongo
    client.close()  # Close client only after fetching data
    ^^^^^^
UnboundLocalError: cannot access local variable 'client' where it is not associated with a value
[2025-02-04T13:46:35.260+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T13:46:35.261+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 13:46:34.995631+00:00 end:2025-02-04 13:46:35.260349+00:00 duration:0.264718
[2025-02-04T13:46:35.261+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_from_mongo> dag:<DAG: idp_fetch_mongo> dagrun:<DagRun idp_fetch_mongo @ 2025-02-03 00:00:00+00:00: scheduled__2025-02-03T00:00:00+00:00, state:running, queued_at: 2025-02-04 13:41:30.262420+00:00. externally triggered: False>
[2025-02-04T13:46:35.261+0000] {logging_mixin.py:190} INFO - Failure caused by cannot access local variable 'client' where it is not associated with a value
[2025-02-04T13:46:35.262+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=idp_fetch_mongo, task_id=fetch_from_mongo, run_id=scheduled__2025-02-03T00:00:00+00:00, execution_date=20250203T000000, start_date=20250204T134634, end_date=20250204T134635
[2025-02-04T13:46:35.273+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T13:46:35.273+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 183 for task fetch_from_mongo (cannot access local variable 'client' where it is not associated with a value; 4809)
Traceback (most recent call last):
  File "/opt/airflow/dags/idp.py", line 17, in fetch_from_mongo
    raise Exception("MONGODB_URI is not set")
Exception: MONGODB_URI is not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/idp.py", line 39, in fetch_from_mongo
    raise Exception(f"The following error occurred: {str(e)}")
Exception: The following error occurred: MONGODB_URI is not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/idp.py", line 42, in fetch_from_mongo
    client.close()  # Close client only after fetching data
    ^^^^^^
UnboundLocalError: cannot access local variable 'client' where it is not associated with a value
[2025-02-04T13:46:35.317+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-04T13:46:35.331+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T13:46:35.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-04T14:05:11.694+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T14:05:11.716+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp_fetch_mongo.fetch_from_mongo scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-04T14:05:11.726+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp_fetch_mongo.fetch_from_mongo scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-04T14:05:11.727+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-04T14:05:11.737+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_from_mongo> on 2025-02-03 00:00:00+00:00
[2025-02-04T14:05:11.772+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=195) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T14:05:11.778+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp_fetch_mongo', 'fetch_from_mongo', 'scheduled__2025-02-03T00:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpiab5me0m']
[2025-02-04T14:05:11.780+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-04T14:05:11.780+0000] {standard_task_runner.py:105} INFO - Job 196: Subtask fetch_from_mongo
[2025-02-04T14:05:11.890+0000] {task_command.py:467} INFO - Running <TaskInstance: idp_fetch_mongo.fetch_from_mongo scheduled__2025-02-03T00:00:00+00:00 [running]> on host 3aa1f743f988
[2025-02-04T14:05:11.999+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp_fetch_mongo' AIRFLOW_CTX_TASK_ID='fetch_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T00:00:00+00:00'
[2025-02-04T14:05:12.003+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-04T14:05:12.003+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-04T14:05:12.004+0000] {logging_mixin.py:190} INFO - Current task name:fetch_from_mongo state:running start_date:2025-02-04 14:05:11.717104+00:00
[2025-02-04T14:05:12.004+0000] {logging_mixin.py:190} INFO - Dag name:idp_fetch_mongo and current dag run status:running
[2025-02-04T14:05:12.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T14:05:12.188+0000] {logging_mixin.py:190} INFO - No projectId provided in DAG run config.
[2025-02-04T14:05:12.189+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-02-04T14:05:12.226+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T14:05:12.226+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp_fetch_mongo, task_id=fetch_from_mongo, run_id=scheduled__2025-02-03T00:00:00+00:00, execution_date=20250203T000000, start_date=20250204T140511, end_date=20250204T140512
[2025-02-04T14:05:12.245+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-04T14:05:12.245+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-04T14:05:12.246+0000] {logging_mixin.py:190} INFO - Dag name:idp_fetch_mongo queued_at:2025-02-04 14:00:05.841932+00:00
[2025-02-04T14:05:12.246+0000] {logging_mixin.py:190} INFO - Task hostname:3aa1f743f988 operator:PythonOperator
[2025-02-04T14:05:12.260+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T14:05:12.272+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T14:05:12.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
