[2025-01-31T08:48:48.508+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T08:48:48.517+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idp.load_to_rabbitmq manual__2025-01-31T08:48:45.442482+00:00 [queued]>
[2025-01-31T08:48:48.603+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idp.load_to_rabbitmq manual__2025-01-31T08:48:45.442482+00:00 [queued]>
[2025-01-31T08:48:48.603+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-31T08:48:48.613+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_rabbitmq> on 2025-01-31 08:48:45.442482+00:00
[2025-01-31T08:48:48.617+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T08:48:48.618+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2025-01-31T08:48:48.618+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'idp', 'load_to_rabbitmq', 'manual__2025-01-31T08:48:45.442482+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/idp.py', '--cfg-path', '/tmp/tmpfrq8lkxo']
[2025-01-31T08:48:48.619+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask load_to_rabbitmq
[2025-01-31T08:48:48.645+0000] {task_command.py:467} INFO - Running <TaskInstance: idp.load_to_rabbitmq manual__2025-01-31T08:48:45.442482+00:00 [running]> on host e5b454575580
[2025-01-31T08:48:48.688+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='idp' AIRFLOW_CTX_TASK_ID='load_to_rabbitmq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T08:48:45.442482+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T08:48:45.442482+00:00'
[2025-01-31T08:48:48.689+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-31T08:48:48.689+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-31T08:48:48.689+0000] {logging_mixin.py:190} INFO - Current task name:load_to_rabbitmq state:running start_date:2025-01-31 08:48:48.517496+00:00
[2025-01-31T08:48:48.689+0000] {logging_mixin.py:190} INFO - Dag name:idp and current dag run status:running
[2025-01-31T08:48:48.690+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T08:48:48.693+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
[2025-01-31T08:48:48.693+0000] {io_services_utils.py:349} ERROR - Socket failed to connect: <socket.socket fd=93, family=10, type=1, proto=6, laddr=('::1', 36336, 0, 0)>; error=111 (Connection refused)
[2025-01-31T08:48:48.693+0000] {connection_workflow.py:375} ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(10, 1, 6, '', ('::1', 5672, 0, 0))
[2025-01-31T08:48:48.693+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-01-31T08:48:48.694+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
[2025-01-31T08:48:48.695+0000] {io_services_utils.py:349} ERROR - Socket failed to connect: <socket.socket fd=93, family=2, type=1, proto=6, laddr=('127.0.0.1', 35732)>; error=111 (Connection refused)
[2025-01-31T08:48:48.695+0000] {connection_workflow.py:375} ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(2, 1, 6, '', ('127.0.0.1', 5672))
[2025-01-31T08:48:48.695+0000] {connection_workflow.py:291} ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-01-31T08:48:48.695+0000] {connection_workflow.py:746} ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused').
[2025-01-31T08:48:48.695+0000] {connection_workflow.py:723} ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-01-31T08:48:48.695+0000] {blocking_connection.py:450} ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
[2025-01-31T08:48:48.695+0000] {blocking_connection.py:457} ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
[2025-01-31T08:48:48.696+0000] {logging_mixin.py:190} INFO - RabbitMQ connection failed: 
[2025-01-31T08:48:48.696+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-31T08:48:48.701+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T08:48:48.701+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=idp, task_id=load_to_rabbitmq, run_id=manual__2025-01-31T08:48:45.442482+00:00, execution_date=20250131T084845, start_date=20250131T084848, end_date=20250131T084848
[2025-01-31T08:48:48.705+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-31T08:48:48.705+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-31T08:48:48.706+0000] {logging_mixin.py:190} INFO - Dag name:idp queued_at:2025-01-31 08:48:45.460843+00:00
[2025-01-31T08:48:48.706+0000] {logging_mixin.py:190} INFO - Task hostname:e5b454575580 operator:PythonOperator
[2025-01-31T08:48:48.719+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T08:48:48.730+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T08:48:48.731+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
